// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://albrfuugjiimogrtepql.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFsYnJmdXVnamlpbW9ncnRlcHFsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODk5MTc4MzQsImV4cCI6MjEwNTQ5MzgzNH0.hY9AWbqujyZ0fY_uL3TfvtMsEH3jlNcK0RrXIeBIgZQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});